# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Réalisations'), (2, 'Services'), (3, 'Réalisations')], null=True),
        ),
    ]
