# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
