# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170129_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
